### ISSUE TITLE
Refers conflict between names-and-places and its-all-data

### ISSUE THREAD

**Issue by timmc** [relevance/labrepl#16]
names-and-places instructs the user to (use 'clojure.contrib.math). its-all-data has (use '[incanter core charts]). If these are both entered in the same REPL session, the following is produced by the second command:

WARNING: group-by already refers to: #'clojure.core/group-by in namespace: incanter.core, being replaced by: #'incanter.core/group-by
java.lang.IllegalStateException: sqrt already refers to: #'clojure.contrib.math/sqrt in namespace: user (repl-1:5)

Subsequently, this chunk of code will fail:

(let
  [f (frequencies (map first words))](view %28bar-chart %28keys f%29 %28vals f%29%29))

with this exception:

java.lang.Exception: Unable to resolve symbol: view in this context (repl-1:9)

**Comment by abedra** [comment]
Good catch.  For now I am going to leave this as is to avoid refer/use confusion in the directions.  If you were to do this in the same REPL session it would look like this:

(require '[incanter core charts])
...  
(let [f (frequencies (map first words))](incanter.core/view %28incanter.charts/bar-chart %28keys f%29 %28vals f%29%29))

this will avoid the namespace conflicts.  I will look into a good way to reorganize/rewrite these labs so that the conflicts don't happen in the future
